### ISSUE TITLE
How to / possible to add label to marker point?

### ISSUE THREAD

**Issue by rlhk** [chrisrzhou/react-globe#17]
As title. Don't see any example or doc mentioning. Thanks!

**Comment by jjwallace** [comment]
`
import React from 'react';
import ReactGlobe from 'react-globe';
import { SpriteText2D, MeshText2D, textAlign } from 'three-text2d'
import * as THREE from 'three';

export default class GlobeBackground extends React.Component {
	constructor(props, context) {
	  super(props, context);
	}

	render() {
	  return (
			
		<ReactGlobe markers={
				this.props.dataArr
			}
			markerOptions={{
				activeScale: 0.01,
				radiusScaleRange: [0.01, 0.01],
				renderer: marker => {

					const { color, id, value } = marker
					var texty = makeTextSprite( "TEXT TITLE", 
						{ 
							fontsize: 32, 
							fontface: "Georgia", 
							borderColor: {r:0, g:0, b:255, a:1.0} 
						} 
					);
					texty.position.set(0,0,0);

					var item = new THREE.Group();

					item.add(texty);
					return item
				},
			}}
			globeOptions={{
				glowCoefficient: 0.1,
				glowColor: 'white',
				glowPower: 4,
				glowRadiusScale: 0.2,
				enableGlow: true,
			}}
			
			// texture: earthTexture,
			cameraOptions={{
				autoRotateSpeed: this.props.rotationSpeed,
				enableAutoRotate: true,
				enableRotate: true,
				maxPolarAngle: (Math.PI * 9) / 16,
				minPolarAngle: (Math.PI * 7) / 16,
				rotateSpeed: 0.4,
			}}/>
	  )
	}
}

`
makeTextSprite.js
`

import React from 'react';
import ReactGlobe from 'react-globe';

import * as THREE from 'three';

export default function makeTextSprite( message, parameters ){
	if ( parameters === undefined ) parameters = {};
	
	var fontface = parameters.hasOwnProperty("fontface") ? 
		parameters["fontface"] : "Arial";
	
	var fontsize = parameters.hasOwnProperty("fontsize") ? 
		parameters["fontsize"] : 18;
	
	var borderThickness = parameters.hasOwnProperty("borderThickness") ? 
		parameters["borderThickness"] : 4;
	
	var borderColor = parameters.hasOwnProperty("borderColor") ?
		parameters["borderColor"] : { r:0, g:0, b:0, a:1.0 };
	
	var backgroundColor = parameters.hasOwnProperty("backgroundColor") ?
		parameters["backgroundColor"] : { r:255, g:255, b:255, a:1.0 };
	var spriteAlignment = 30;//THREE.SpriteAlignment.topLeft;
		
	var canvas = document.createElement('canvas');
	var context = canvas.getContext('2d');
	context.font = "Bold " + fontsize + "px " + fontface;
	
	// get size data (height depends only on font size)
	var metrics = context.measureText( message );
	var textWidth = metrics.width;
	
	// background color
	context.fillStyle   = "rgba(" + backgroundColor.r + "," + backgroundColor.g + ","
									+ backgroundColor.b + "," + backgroundColor.a + ")";
	// border color
	context.strokeStyle = "rgba(" + borderColor.r + "," + borderColor.g + ","
									+ borderColor.b + "," + borderColor.a + ")";
	context.lineWidth = borderThickness;
	roundRect(context, borderThickness/2, borderThickness/2, textWidth + borderThickness, fontsize * 1.4 + borderThickness, 6);
	// 1.4 is extra height factor for text below baseline: g,j,p,q.
	
	// text color
	context.fillStyle = "rgba(0, 0, 0, 1.0)";
	context.fillText( message, borderThickness, fontsize + borderThickness);
	
	// canvas contents will be used for a texture
	var texture = new THREE.Texture(canvas) 
	texture.needsUpdate = true;
	var spriteMaterial = new THREE.SpriteMaterial( 
		{ map: texture} ); //, useScreenCoordinates: false, alignment: spriteAlignment }
	var sprite = new THREE.Sprite( spriteMaterial );
	sprite.scale.set(100,50,1.0);
	return sprite;	
}

function roundRect(ctx, x, y, w, h, r) {
	ctx.beginPath();
	ctx.moveTo(x+r, y);
	ctx.lineTo(x+w-r, y);
	ctx.quadraticCurveTo(x+w, y, x+w, y+r);
	ctx.lineTo(x+w, y+h-r);
	ctx.quadraticCurveTo(x+w, y+h, x+w-r, y+h);
	ctx.lineTo(x+r, y+h);
	ctx.quadraticCurveTo(x, y+h, x, y+h-r);
	ctx.lineTo(x, y+r);
	ctx.quadraticCurveTo(x, y, x+r, y);
	ctx.closePath();
	ctx.fill();
	ctx.stroke();   
}






`

**Comment by rlhk** [comment]
Thanks for the detailed example. 
Hopefully the feature could be supported by component props in future as I find it not a rare use case.

**Comment by chrisrzhou** [comment]
Thanks for raising the issue `rlhk`.  Due to how customizable `labels` can look, I think it's best to defer this to custom rendering using the `markerRenderer` functionality.  It is a fairly common use case, but finding a way to make this look good in a generic way is hard.  Happy to accept a PR that adds to the documentation on a good "recipe" for rendering labels in a nice way!
