### ISSUE TITLE
Callback onClick

### ISSUE THREAD

**Issue by Pure-Digital** [chrisrzhou/react-globe#19]
Is it possible to get x y coordinates of pointer, when clicking somewhere on globe?

I am looking for a way to add marker on globe where the user clicks. So far, I can't find any event where I can obtain this info.

**Comment by chrisrzhou** [comment]
@Pure-Digital, the [Callbacks docs](https://react-globe.netlify.com/examples/callbacks) show how to get `pointerEventPosition`.  This is passed as the third argument of `onClickMarker` (typed as `MarkerCallback`).  Let me know if this helps!
