### ISSUE TITLE
Prevent Zoom When Marker Clicked

### ISSUE THREAD

**Issue by a-kud** [chrisrzhou/react-globe#26]
Hello. Is there a way to stop globe from spinning and to prevent zoom to the marker when user clicks it?

**Comment by chrisrzhou** [comment]
Hi @a-kud, if you used the `Globe` instance via `onGetGlobeInstance`, you can have access to `.freeze()` and `.unfreeze()` methods.  You can probably use this to have more control to prevent zooming.

**Comment by mledwards** [comment]
Do you mean `lock()` and `unlock()`? Also `lock()` doesn't seem to work in the `onClickMarker` function, as I want to stop rotation.
