### ISSUE TITLE
is it possible to animate between 2 markers?

### ISSUE THREAD

**Issue by RichMatthews** [chrisrzhou/react-globe#28]
Hey cool app! really like it

just wondering if you had a feature where I could navigate between 2 markers/points and animate the movement between the two? would love to be able to show a plane moving between 2 countries or something

let me know

**Comment by chrisrzhou** [comment]
Hey @RichMatthews, thanks for checking out the repo.  Animations can only be controlled/set on the Globe through the `options` property or `animations` prop.  I think what you're looking to do here is fairly custom and is not possible to do with this component (only the globe can be animated by controlling the camera, nothing else).

If you get this custom example working in your own ThreeJS code, I would love to see it.  Sounds like there would be a good use case for defining custom animations between two points in a `SphereGeometry`!
