### ISSUE TITLE
Animated Markers

### ISSUE THREAD

**Issue by Jehutty** [chrisrzhou/react-globe#3]
HI there @chrisrzhou does the globe support animated markers as in your google trends app? If so, I suppose its a custom renderer of a marker to be used, but how does three.js is used to perform that effect?

**Comment by chrisrzhou** [comment]
Hi @Jehutty, `react-globe` will only provide very basic dot/bar marker rendering but allows you to write your own custom markers by providing a valid render method in `markerOptions.renderer`.  The goal of this function is to take the `Marker` data object and return a valid `THREE.Object3D` object.  `react-globe` will place it correctly as well as support interaction events.

In `google-globe-trends` app, this is the code that I used: https://github.com/chrisrzhou/google-globe-trends/blob/master/src/markerRenderer.ts . It is possible to build really beautiful and animated markers with `renderer` (similar to the higher quality markers viewed in the metoorising project).

**Comment by Jehutty** [comment]
Hi @chrisrzhou thank you for your insight that clarified a lot and got me started on creating my own meshes, I would like to have a dynamic size for them depending on the current distance the camera is at any point. Is there a getter for the distanceRadiusScale so I can play arround with it ?

**Comment by chrisrzhou** [comment]
Hmm, currently there are no getters in the component. Right now the component doesn't really interface with the camera much except with `cameraOptions`.  The camera code is also largely managed by OrbitControls, so I don't think it will be simple to grab this specific value.

One way to approach this is to potentially expose all the ThreeJS ref objects (Camera, Globe, OrbitControls) so users can hijack and control it from outside.  But not 100% confident that I want to expand on this API until I get a better understanding.  Let me know if you find any work around and curious to see how you are implementing your custom marker rendering :)

**Comment by Jehutty** [comment]
Hey Chris I’m getting into typescript to get a better understanding of how
this works seems pretty easy and useful to write compact hard typed js
This was my conclusion as well I’m looking into a native globe three js to
understand how orbit controls work then try to expand on your interface.
I’ll fork it and will start working on it this weekend. This thing got a
lot of potential for powerful visualisations good work dude!
