### ISSUE TITLE
Markers floating

### ISSUE THREAD

**Issue by Jehutty** [chrisrzhou/react-globe#5]
Is it possible to change the z axis of the markers to appear on the same layer of the surface of the globe, through the current Marker component props or a custom renderer, or is the problem deeper than that?

**Comment by chrisrzhou** [comment]
Hi @jehutty it might be deeper than that and I think I ran into it once. If you can include a codesandbox example that reproduces this issue (in an exaggerated situation) I can help look into the issue.

Might be able to get to it next week along with the other Github issues

**Comment by chrisrzhou** [comment]
This is now supported with `offsetRadiusScale` in the `markersOptions` prop.  Check out the [codesandbox example](https://codesandbox.io/s/react-globe-311-cdp92) and play around with `offsetRadiusScale` (your use case is set at `offsetRadiusScale: 0`).

The docs is also updated and you can refer to the behavior in the `Props > Types > MarkersOptions > offsetRadiusScale` section.

Closing the issue now!
