### ISSUE TITLE
How to set custom point Sydney for example as default center of globe

### ISSUE THREAD

**Issue by xwenc** [chrisrzhou/react-globe#6]
Hi Chris, 

  Thank you very much for sharing this excellent globe.  I want to ask you how can I set custom point, for example, Syndey's coordinates, as default center of the globe?

**Comment by chrisrzhou** [comment]
Hi @xwenc, try using the `lookAt` props (see [code](https://github.com/chrisrzhou/react-globe/blob/master/src/ReactGlobe.tsx#L52)).

Let me know if that is what you're looking for!

**Comment by xwenc** [comment]
Yes, That's what i want, thanks！  O(∩_∩)O
