### ISSUE TITLE
Could not find a declaration file for module 'three-orbitcontrols'.

### ISSUE THREAD

**Issue by mavrickp** [chrisrzhou/react-globe#7]
1 | import { useEffect, useRef } from 'react';
    2 | import { AmbientLight, Color, PerspectiveCamera, PointLight } from 'three';
  > 3 | import OrbitControls from 'three-orbitcontrols';
      |                           ^
    4 | 
    5 | import {
    6 |   CAMERA_DAMPING_FACTOR,

**Comment by chrisrzhou** [comment]
Hi @mavrickp, I fixed the Typescript types in 3.1.1 ([codesandbox example](https://codesandbox.io/s/react-globe-311-cdp92)).  Please install the latest version with `yarn/npm`!

For your specific example, it seems you are calling `three-orbitcontrols` in your project.  This library is untyped so I think you need to declare it as a module in a `module.d.ts` file in your project.  If you are just using `react-wordcloud`, you should not need to access orbit controls, and this problem might go away.

Closing the issue!
